name: Backend CI

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  backend-CI:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Format
      run: npm run format --if-present
    
    - name: Lint
      run: npm run lint --if-present
    
    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm run test --if-present
